#网站配置
website:
  #网站名
  name: 栗书文学
  #域名
  domain: lizhireader.com
  #SEO关键词
  keyword: ${website.name},小说,原创文学，精品女频,遇见阅读，遇见更美好的你
  #SEO描述
  description: ${website.name}是一个多端（PC、WAP）原创文学阅读网，
  #联系QQ
  qq: 344970952
